CREATE SEQUENCE customer_seq
  START WITH 1
  INCREMENT BY 1
  NO MAXVALUE
  NO MINVALUE
  CACHE 1;

CREATE TABLE CustomerProfile
(
  id   INT         NOT NULL,
  name VARCHAR(20) NOT NULL
);

ALTER TABLE CustomerProfile
  ADD CONSTRAINT customer_profile_pk PRIMARY KEY (id)
;

CREATE SEQUENCE account_seq
  START WITH 1
  INCREMENT BY 1
  NO MAXVALUE
  NO MINVALUE
  CACHE 1;

CREATE TABLE Account
(
  id         INT       NOT NULL,
  Accountid  INT       NOT NULL,
  customerid INT,
  Balance    FLOAT(20) NOT NULL
);

ALTER TABLE Account
  ADD CONSTRAINT account_pk PRIMARY KEY (id);

ALTER TABLE Account
  ADD CONSTRAINT customer_profile_fk FOREIGN KEY (customerid) REFERENCES CustomerProfile (id);

INSERT INTO CUSTOMERPROFILE
VALUES (1, 'TEST_CUSTOMER_1');
INSERT INTO ACCOUNT
VALUES (101, 11, 500, 1);

INSERT INTO CUSTOMERPROFILE
VALUES (2, 'TEST_CUSTOMER_2');
INSERT INTO ACCOUNT
VALUES (102, 12, 2500, 2);

INSERT INTO CUSTOMERPROFILE
VALUES (3, 'TEST_CUSTOMER_3');
INSERT INTO ACCOUNT
VALUES (103, 13, 2500, 3);
